import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {MessageCircle,Send,ShieldCheck} from 'lucide-react';
import {api} from '../lib/api';
import type {List,Row} from '../lib/api';
import {useData} from '../lib/hooks';
import {Badge,ErrorBox,SectionHeader} from '../components/ui';

export function Conversation(){
 const [revision,refresh]=useState(0),[messages,setMessages]=useState<Row[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const sessions=useData<List>('/conversations',revision),bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true;const session=sessions.data?.data.find(s=>s.channel==='INTERNAL');if(session)api<List>('/conversations/'+session.id+'/messages').then(r=>{if(active)setMessages(r.data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false};},[sessions.data]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages]);
 async function send(value:string){if(!value.trim()||busy)return;setBusy(true);setError('');try{await api('/conversations/messages','POST',{text:value});setText('');refresh(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();await send(text);}
 return <><SectionHeader title="Vamos conversar" subtitle="Conte o que aconteceu. A gente organiza os detalhes."><Badge tone="green"><ShieldCheck size={14}/>Confirmação antes de registrar receitas</Badge></SectionHeader><div className="conversation-layout"><section className="chat-panel"><div className="chat-heading"><div className="bot-avatar"><MessageCircle size={22}/></div><div><strong>Assistente Cacau</strong><p>Finanças da sua família</p></div><span className="dot green"/></div><div className="chat-messages">{!messages.length&&<div className="chat-welcome"><span>Olá 👋</span><h2>O que vamos registrar hoje?</h2><p>“Recebi 770 Paciente Alice.”</p><small>Se faltar pessoa, trabalho ou conta, vou perguntar e oferecer opções.</small></div>}{messages.map((m,index)=><div className="chat-pair" key={m.id}><div className="bubble user">{m.normalized_text||'Áudio em processamento'}</div>{m.response&&<div className="bubble bot"><p>{index===messages.length-1&&m.response.choices?.length?m.response.question.split('\n1. ')[0]:m.response.question}</p>{m.response.status==='CONFIRMED'&&<Badge tone="green">Registrado</Badge>}{m.response.status==='WAITING_CONFIRMATION'&&<Badge tone="amber">Aguardando sua confirmação</Badge>}{index===messages.length-1&&['WAITING_INFORMATION','WAITING_CONFIRMATION'].includes(m.response.status)&&m.response.choices?.length>0&&<div className="chat-choices">{m.response.choices.map((choice:{label:string;value:string})=><button type="button" className="choice-option" key={choice.value} disabled={busy} onClick={()=>send(choice.value)}>{choice.value}. {choice.label}</button>)}</div>}</div>}</div>)}<div ref={bottom}/></div><ErrorBox message={error}/><form className="chat-compose" onSubmit={submit}><input aria-label="Mensagem para o assistente" value={text} onChange={e=>setText(e.target.value)} placeholder="Escreva uma mensagem ou escolha uma opção…" maxLength={8000} required/><button className="primary" disabled={busy||!text.trim()} aria-label="Enviar mensagem"><Send size={19}/></button></form></section><aside className="conversation-tips"><h3>Clareza em cada registro</h3><div><span>01</span><h4>Conte naturalmente</h4><p>“Recebi 770 Paciente Alice” ou “Gastei 128 de gasolina”.</p></div><div><span>02</span><h4>Escolha a opção</h4><p>Toque na resposta aqui. No WhatsApp, envie o número ou escreva o nome.</p></div><div><span>03</span><h4>Confirme antes de registrar</h4><p>Uma receita só entra no financeiro depois de você conferir pessoa, trabalho, valor, conta e data.</p></div><p className="form-hint">No WhatsApp vinculado, texto e áudio seguem as mesmas regras. Esta tela recebe texto.</p></aside></div></>;
}
