import {useState} from 'react';
import type {FormEvent} from 'react';
import {Plus,Archive,Pencil,Wallet,Target,ArrowUpRight,Link2} from 'lucide-react';
import {api,currency,dateLabel,today} from '../lib/api';
import type {List,Row} from '../lib/api';
import {useData} from '../lib/hooks';
import {Badge,Empty,ErrorBox,Loading,Modal,SectionHeader} from '../components/ui';
type Field = {key:string;label:string;type?:string;options?:[string,string][];resource?:string;optional?:boolean;value?:string};
const name:Field={key:'name',label:'Nome'};
const accountField:Field={key:'linked_account_id',label:'Conta correspondente (evita somar duas vezes)',resource:'accounts',optional:true};
export const catalogs:Record<string,{title:string;subtitle:string;fields:Field[];amount?:string}>={
 accounts:{title:'Contas',subtitle:'Seu dinheiro disponível, organizado por conta.',amount:'balance',fields:[name,{key:'kind',label:'Tipo',options:[['CHECKING','Conta corrente'],['SAVINGS','Poupança'],['CASH','Dinheiro'],['INVESTMENT','Investimento']]},{key:'opening_balance',label:'Saldo de abertura (R$)',type:'money',value:'0.00'},{key:'opening_balance_date',label:'Data do saldo de abertura',type:'date'},{key:'is_emergency_reserve',label:'Esta conta é reserva de emergência',type:'checkbox'}]},
 cards:{title:'Cartões',subtitle:'Compras, parcelas e faturas em um único lugar.',amount:'limit_amount',fields:[name,{key:'issuer',label:'Instituição',optional:true},{key:'closing_day',label:'Dia de fechamento',type:'day'},{key:'due_day',label:'Dia de vencimento',type:'day'},{key:'limit_amount',label:'Limite (R$)',type:'money',optional:true},{key:'default_payment_account_id',label:'Conta prevista para pagar a fatura',resource:'accounts',optional:true}]},
 categories:{title:'Categorias',subtitle:'Classifique pela natureza da compra, além do estabelecimento.',fields:[name,{key:'kind',label:'Tipo',options:[['EXPENSE','Despesa'],['INCOME','Receita']]},{key:'parent_id',label:'Categoria principal',resource:'categories',optional:true},{key:'is_essential',label:'Despesa essencial',type:'checkbox'}]},
 merchants:{title:'Estabelecimentos',subtitle:'Identifique onde cada compra foi realizada.',fields:[name]},
 'category-rules':{title:'Regras de categorias',subtitle:'Regras explícitas para organizar novos lançamentos.',fields:[{key:'pattern',label:'Palavra ou expressão'},{key:'match_type',label:'Correspondência',options:[['CONTAINS','Contém a expressão'],['EXACT','Texto exato']]},{key:'category_id',label:'Categoria',resource:'categories'},{key:'priority',label:'Prioridade',type:'number',value:'0'},{key:'confidence',label:'Confiança (0 a 1)',type:'confidence',value:'0.95'},{key:'enabled',label:'Regra ativa',type:'checkbox',value:'true'}]},
 goals:{title:'Metas',subtitle:'Dê um destino ao dinheiro que você está construindo.',amount:'target_amount',fields:[name,{key:'target_amount',label:'Valor objetivo (R$)',type:'money'},{key:'target_date',label:'Prazo desejado',type:'date',optional:true}]},
 assets:{title:'Ativos',subtitle:'Bens e investimentos que compõem seu patrimônio.',amount:'valuation',fields:[name,{key:'kind',label:'Tipo',options:[['PROPERTY','Imóvel'],['VEHICLE','Veículo'],['INVESTMENT','Investimento'],['OTHER','Outro']]},{key:'valuation',label:'Avaliação (R$)',type:'money'},{key:'valuation_date',label:'Data da avaliação',type:'date'},accountField]},
 liabilities:{title:'Passivos',subtitle:'Obrigações que precisam entrar na sua visão patrimonial.',amount:'outstanding_amount',fields:[name,{key:'outstanding_amount',label:'Saldo devedor (R$)',type:'money'},{key:'valuation_date',label:'Data da avaliação',type:'date'},{key:'due_date',label:'Vencimento',type:'date',optional:true},{key:'linked_credit_card_id',label:'Cartão correspondente (evita somar duas vezes)',resource:'cards',optional:true}]},
};
export function Resources({resource,navigate}:{resource:string;navigate:(path:string)=>void}) {
 const config=catalogs[resource];const [revision,refresh]=useState(0),[editing,setEditing]=useState<Row|null|undefined>(null),[goal,setGoal]=useState<Row|null>(null),[error,setError]=useState('');const result=useData<List>('/'+resource,revision);
 async function archive(row:Row){if(!confirm('Arquivar '+row.name+'? O histórico será preservado.'))return;try{await api('/'+resource+'/'+row.id+'/archive','POST',{expected_version:row.version});refresh(revision+1);}catch(e){setError((e as Error).message);}}
 return <><SectionHeader title={config.title} subtitle={config.subtitle}><button className="primary" onClick={()=>setEditing(undefined)}><Plus size={18}/>Adicionar</button></SectionHeader><ErrorBox message={error||result.error}/>{resource==='cards'&&<button className="review-link" onClick={()=>navigate('/finances/invoices')}>Ver faturas e pagamentos <ArrowUpRight size={17}/></button>}{result.loading?<Loading/>:!result.data?.data.length?<section className="panel"><Empty>Adicione o primeiro registro para começar.</Empty></section>:<div className="resource-grid">{result.data.data.map(row=><article key={row.id} className={'resource-card '+(row.archived_at?'archived':'')}><div className="resource-top"><div className="resource-icon">{resource==='goals'?<Target size={22}/>:<Wallet size={22}/>}</div>{row.archived_at?<Badge>Arquivado</Badge>:<Badge tone="green">{row.status==='COMPLETED'?'Concluído':'Ativo'}</Badge>}</div><h2>{row.name||row.pattern}</h2>{config.amount&&<strong className="resource-value">{currency(row[config.amount])}</strong>}{resource==='cards'&&<p>Fecha dia {row.closing_day} · Vence dia {row.due_day}</p>}{resource==='goals'&&<p>{row.target_date?'Até '+dateLabel(row.target_date):'No seu ritmo'}</p>}{resource==='accounts'&&<p>{row.is_emergency_reserve?'Reserva de emergência':'Saldo realizado, sem limite de crédito'}</p>}<div className="resource-actions"><button className="text-button" onClick={()=>setEditing(row)}><Pencil size={15}/>Editar</button>{resource==='goals'?<button className="text-button" onClick={()=>setGoal(row)}>Contribuir <Plus size={15}/></button>:('archived_at' in row)&&!row.archived_at&&<button className="icon-button" aria-label={'Arquivar '+row.name} onClick={()=>archive(row)}><Archive size={16}/></button>}</div></article>)}</div>}{editing!==null&&<Modal title={(editing?'Editar: ':'Adicionar: ')+config.title} onClose={()=>setEditing(null)}><ResourceForm resource={resource} fields={config.fields} initial={editing} onDone={()=>{setEditing(null);refresh(revision+1);}} onCancel={()=>setEditing(null)}/></Modal>}{goal&&<Modal title={'Contribuir · '+goal.name} onClose={()=>setGoal(null)}><Contribution goal={goal} onDone={()=>{setGoal(null);refresh(revision+1);}}/></Modal>}</>;
}
function FieldInput({field,initial}:{field:Field;initial?:Row}) {const result=useData<List>('/'+(field.resource||'accounts'));const value=initial?.[field.key]??field.value??(field.type==='date'&&!field.optional?today():'');return <label className={field.type==='checkbox'?'checkbox-label full':''}>{field.type==='checkbox'?<><input name={field.key} type="checkbox" defaultChecked={value===true||value==='true'}/>{field.label}</>:<>{field.label}{field.optional&&<small>Opcional</small>}{field.options||field.resource?<select name={field.key} required={!field.optional} defaultValue={value}><option value="">Selecione</option>{field.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}{field.resource&&result.data?.data.filter(r=>!r.archived_at&&r.id!==initial?.id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>:<input name={field.key} type={field.type==='date'?'date':['money','number','day','confidence'].includes(field.type||'')?'number':'text'} required={!field.optional} defaultValue={value} step={field.type==='money'||field.type==='confidence'?'0.01':'1'} min={field.type==='day'?1:field.type==='confidence'?0:undefined} max={field.type==='day'?31:field.type==='confidence'?1:undefined}/>}</>}</label>;}
function ResourceForm({resource,fields,initial,onDone,onCancel}:{resource:string;fields:Field[];initial?:Row;onDone:()=>void;onCancel:()=>void}) {const [error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),values:Record<string,unknown>={};for(const f of fields){const v=form.get(f.key);values[f.key]=f.type==='checkbox'?v==='on':v===''&&f.optional?null:['number','day','confidence'].includes(f.type||'')?Number(v):v;}setBusy(true);try{await api('/'+resource+(initial?'/'+initial.id:''),initial?'PATCH':'POST',initial?{expected_version:initial.version,changes:values}:values);onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <form className="form-grid" onSubmit={submit}><ErrorBox message={error}/>{fields.map(f=><FieldInput key={f.key} field={f} initial={initial}/>)}<div className="form-actions full"><button type="button" className="secondary" onClick={onCancel}>Cancelar</button><button disabled={busy} className="primary">{busy?'Salvando…':'Salvar'}</button></div></form>;}
function Contribution({goal,onDone}:{goal:Row;onDone:()=>void}) {const [error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/goals/'+goal.id+'/contributions','POST',{amount:f.get('amount'),contribution_date:f.get('date'),direction:f.get('direction')});onDone();}catch(e){setError((e as Error).message);}}return <form onSubmit={submit} className="form-grid"><ErrorBox message={error}/><label>Valor<input name="amount" type="number" step="0.01" min="0.01" required/></label><label>Data<input name="date" type="date" defaultValue={today()} required/></label><label>Operação<select name="direction"><option value="ADD">Adicionar à meta</option><option value="WITHDRAW">Retirar da meta</option></select></label><p className="form-hint full">A contribuição é uma alocação para a meta. Ela não cria uma despesa.</p><button className="primary">Confirmar contribuição</button></form>;}
export function Invoices(){const [revision,refresh]=useState(0),[selected,setSelected]=useState<Row|null>(null),[error,setError]=useState('');const invoices=useData<List>('/invoices',revision),cards=useData<List>('/cards').data?.data||[],accounts=useData<List>('/accounts').data?.data||[];async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/invoices/'+selected!.id+'/payments','POST',{amount:f.get('amount'),account_id:f.get('account'),transaction_date:f.get('date')});setSelected(null);refresh(revision+1);}catch(e){setError((e as Error).message);}}return <><SectionHeader title="Faturas" subtitle="Pagar a fatura movimenta sua conta sem repetir as despesas."/><ErrorBox message={invoices.error}/><section className="panel">{invoices.loading?<Loading/>:!invoices.data?.data.length?<Empty title="Nenhuma fatura">As compras no crédito serão agrupadas aqui.</Empty>:invoices.data.data.map(i=><div className="simple-row" key={i.id}><div><strong>{cards.find(c=>c.id===i.credit_card_id)?.name||'Cartão'}</strong><p>Vencimento {dateLabel(i.due_date)} · Fechamento {dateLabel(i.closing_date)}</p></div><Badge tone={i.status==='PAID'?'green':'amber'}>{i.status==='PAID'?'Paga':i.status==='PARTIALLY_PAID'?'Parcialmente paga':'Em aberto'}</Badge><strong>{currency(i.balance)}</strong><button className="secondary" disabled={i.balance==='0.00'} onClick={()=>{setError('');setSelected(i);}}>Pagar</button></div>)}</section>{selected&&<Modal title="Registrar pagamento da fatura" onClose={()=>setSelected(null)}><form className="form-grid" onSubmit={pay}><ErrorBox message={error}/><label>Conta de pagamento<select name="account" required><option value="">Selecione</option>{accounts.filter(a=>!a.archived_at).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Valor<input name="amount" type="number" step="0.01" min="0.01" defaultValue={selected.balance} required/></label><label>Data do pagamento<input name="date" type="date" defaultValue={today()} required/></label><button className="primary">Confirmar pagamento</button></form></Modal>}</>;}
