import {useState} from 'react';
import type {FormEvent} from 'react';
import {api, today} from '../lib/api';
import type {List, Row} from '../lib/api';
import {useData} from '../lib/hooks';
import {ErrorBox} from '../components/ui';
export function TransactionForm({initial,onDone,onCancel,importRow}:{initial?:Row;onDone:()=>void;onCancel:()=>void;importRow?:{jobId:string;rowId:string;version:number}}) {
 const accounts=useData<List>('/accounts').data?.data||[],cards=useData<List>('/cards').data?.data||[],categories=useData<List>('/categories').data?.data||[];
 const initialSource=initial?.financial_source || (initial?.credit_card_id?{kind:'CREDIT_CARD',id:initial.credit_card_id}:initial?.destination_account_id?{kind:'ACCOUNT_TRANSFER',source_id:initial.account_id,destination_id:initial.destination_account_id}:{kind:'ACCOUNT',id:initial?.account_id});
 const [type,setType]=useState(initial?.type||'EXPENSE'),[sourceKind,setSourceKind]=useState(initialSource.kind),[sourceId,setSourceId]=useState(initialSource.id||initialSource.source_id||''),[destination,setDestination]=useState(initialSource.destination_id||'');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>) {event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);
  const source=type==='TRANSFER'?{kind:'ACCOUNT_TRANSFER',source_id:sourceId,destination_id:destination}:{kind:sourceKind,id:sourceId};
  const values={type,amount:String(form.get('amount')),transaction_date:form.get('date'),description:form.get('description'),status:form.get('status'),category_id:type==='TRANSFER'?null:form.get('category')||null,financial_source:source,...(!initial&&!importRow?{installment_count:Number(form.get('installments')||1)}:{})};
  try {if(importRow)await api(`/imports/${importRow.jobId}/rows/${importRow.rowId}`,'PATCH',{expected_version:importRow.version,changes:values});else if(initial)await api('/transactions/'+initial.id,'PATCH',{expected_version:initial.version,changes:values});else await api('/transactions','POST',values);onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <form onSubmit={submit} className="form-grid"><ErrorBox message={error}/><label>Tipo<select value={type} onChange={e=>{setType(e.target.value);setSourceKind('ACCOUNT');setSourceId('');}}><option value="EXPENSE">Despesa</option><option value="INCOME">Receita</option><option value="TRANSFER">Transferência entre contas</option></select></label><label>Valor (R$)<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={initial?.amount} placeholder="0,00"/></label><label className="full">Descrição<input name="description" required maxLength={500} defaultValue={initial?.description} placeholder="Ex.: Compras no supermercado" autoFocus/></label><label>Data<input name="date" type="date" required defaultValue={initial?.transaction_date||today()}/></label><label>Situação<select name="status" defaultValue={initial?.status==='PLANNED'?'PLANNED':'POSTED'}><option value="POSTED">Realizado</option><option value="PLANNED">Previsto</option></select></label>{type==='EXPENSE'&&<label>Forma de pagamento<select value={sourceKind} onChange={e=>{setSourceKind(e.target.value);setSourceId('');}}><option value="ACCOUNT">Conta / débito / Pix</option><option value="CREDIT_CARD">Cartão de crédito</option></select></label>}<label>{type==='TRANSFER'?'Conta de origem':sourceKind==='CREDIT_CARD'?'Cartão':'Conta'}<select required value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Selecione explicitamente</option>{(sourceKind==='CREDIT_CARD'&&type==='EXPENSE'?cards:accounts).filter(a=>!a.archived_at).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{type==='TRANSFER'?<label>Conta de destino<select required value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Selecione</option>{accounts.filter(a=>!a.archived_at&&a.id!==sourceId).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>:<label>Categoria<select name="category" defaultValue={initial?.category_id||''}><option value="">Sem categoria</option>{categories.filter(c=>c.kind===type&&!c.archived_at).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{!initial&&!importRow&&sourceKind==='CREDIT_CARD'&&<label>Parcelas<input name="installments" type="number" min="1" max="120" defaultValue="1" required/></label>}<p className="form-hint full">Confira valor, data e fonte antes de salvar. Datas futuras serão registradas como previstas.</p><div className="form-actions full"><button type="button" className="secondary" onClick={onCancel}>Cancelar</button><button disabled={busy} className="primary">{busy?'Salvando…':'Salvar lançamento'}</button></div></form>;
}
